### ISSUE TITLE
remove dependency on `compiler_builtins`

### ISSUE THREAD

**Issue by japaric** [japaric/cortex-m-rt#31]
That crate is an implementation detail of the compiler. It contains the implementation of intrinsics that LLVM may emit calls to when lowering Rust code to machine code. It's unknown what the future of `compiler_builtins` will be but likely it will not exist in the future (it *might* be merged into the core crate).

So this a breaking change that will come from upstream at some point: `extern crate compiler_builtins` is unstable.

**Comment by djmcgill** [comment]
How will this change be effected? Just delete all references to `compiler_builtins` and then the user must include and link it themselves to use this crate?

I'm very happy to start work on this.

**Comment by japaric** [comment]
I think we should not change things right now. Because if we do we are going to break code *and* incovenience all application writers (they'll now have to manually link to compiler-builtins), and *then* whenever the Rust team makes a decision about compiler-builtins things are likely going to break *again*.

I would prefer to maintain the status quo until an official decision is made about compiler-builtins.
