### ISSUE TITLE
Depend on a no_std compatible version of chrono

### ISSUE THREAD

**Issue by robomancer-or** [japaric/cortex-m-rt#60]
I'm running into a dependency conflict where I can't depend on `uom` because it depends on `num-traits`, which has been made no_std compatible since the most recent version of `chrono`.  The problem is, the released version of `chrono` depends on a conflicting version of `num-traits` that requires `std`.  Why cargo can't sort out conflicts of this sort is beyond me, but since it can't, would `cortex-m-rt` switching to the github version of `chrono` be permissible (at least until `chrono` gets their act together and cuts a no_std compatible release)?

To recreate the problem for yourself, all you have to do is start a blank no_std library project, add a dep for

    uom = { git = "https://github.com/iliekturtles/uom", branch = "dev-num-std", default-features=false, features =["si", "f32"] }

verify that xargo can build it, then add a dep for `cortex-m-rt = "*"` and try to build again

**Comment by hannobraun** [comment]
> would `cortex-m-rt` switching to the github version of `chrono` be permissible (at least until `chrono` gets their act together and cuts a no_std compatible release)?

I'd like to note that crates.io doesn't accept crates that depend on git repositories, so switching to chrono's GitHub version would effectively block new versions of cortex-m-rt from being released.

**Comment by robomancer-or** [comment]
...Oh, I definitely didn't realize that, yeah, that's definitely not worth it!

**Comment by skierpage** [comment]
https://crates.io/crates/chrono is now at 0.4.1 which is no_std compatible. \o/?

**Comment by whitequark** [comment]
Note that because of https://github.com/rust-lang/cargo/issues/4866 it is not enough for chrono to support `no_std` to handle every case. Dropping it is the right approach.
